export const USER_ACTION_TYPES = {
  FETCH_USER_START: 'user/FETCH_USER_START',
  FETCH_USER_SUCCESS: 'user/FETCH_USER_SUCCESS',
  FETCH_USER_FAILED: 'user/FETCH_USER_FAILED',
  CHANGE_USER_STATUS_START: 'user/CHANGE_USER_STATUS_START',
  CHANGE_USER_STATUS_SUCCESS: 'user/CHANGE_USER_STATUS_SUCCESS',
  CHANGE_USER_STATUS_FAILED: 'user/CHANGE_USER_STATUS_FAILED',
  SET_USER_RESPONSE_NULL: 'user/SET_USER_RESPONSE_NULL',
  ADD_USER_START: 'user/ADD_USER_START',
  ADD_USER_SUCCESS: 'user/ADD_USER_SUCCESS',
  ADD_USER_FAILED: 'user/ADD_USER_FAILED',
  UPDATE_USER_START: 'user/UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'user/UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED: 'user/UPDATE_USER_FAILED'
}
