export const AUTH_ACTION_TYPES = {
    LOGIN_USER_START: 'auth/LOGIN_USER_START',
    LOGIN_USER_START_SUCCESS: 'auth/LOGIN_USER_START_SUCCESS',
    LOGIN_USER_START_FAILED: 'auth/LOGIN_USER_START_FAILED',
    CHANGE_PASSWORD_START: 'auth/CHANGE_PASSWORD_START',
    CHANGE_PASSWORD_SUCCESS: 'auth/CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILED: 'auth/CHANGE_PASSWORD_FAILED',
    GET_LOGGED_IN_DETAILS_START: 'auth/GET_LOGGED_IN_DETAILS_START',
    GET_LOGGED_IN_DETAILS_SUCCESS: 'auth/GET_LOGGED_IN_DETAILS_SUCCESS',
    GET_LOGGED_IN_DETAILS_FAILED: 'auth/GET_LOGGED_IN_DETAILS_FAILED',
    SET_RESPONSE_NULL: 'auth/SET_RESPONSE_NULL'
}
