export const AUTH_ACTION_TYPES = {
    LOGIN_USER_START: 'auth/LOGIN_USER_START',
    LOGIN_USER_START_SUCCESS: 'auth/LOGIN_USER_START_SUCCESS',
    LOGIN_USER_START_FAILED: 'auth/LOGIN_USER_START_FAILED',
    SET_RESPONSE_NULL: 'auth/SET_RESPONSE_NULL'
}
