export const CMS_ACTION_TYPES = {
  FETCH_CMS_START: 'cms/FETCH_CMS_START',
  FETCH_CMS_SUCCESS: 'cms/FETCH_CMS_SUCCESS',
  FETCH_CMS_FAILED: 'cms/FETCH_CMS_FAILED',
  SHOW_CMS_START: 'user/SHOW_CMS_START',
  SHOW_CMS_SUCCESS: 'user/SHOW_CMS_SUCCESS',
  SHOW_CMS_FAILED: 'user/SHOW_CMS_FAILED',
  SET_CMS_RESPONSE_NULL: 'cms/SET_CMS_RESPONSE_NULL'
}
